spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    # password: '{cipher}ac5c9144f78425928bd15e4d9a001d1a24dafccc3031382db697680132fcdfa6'  # 1234
    password: '{cipher}AQAkqT/oPMLGZCTSyLtNMkqo54YQslU5gZ9SNaAS41wYCkRfqTV8N5A5ZIaBahZNOTX3TxQWo5AxfCW5QBZpaRorOVgQpVaI49lE+oq7QOAJXx/Lj/MM+u8h9on9yF7LJb9Wt+uv2djEkolQzBZXPqL5u0Op9wnM426z1KDbleFm2/By1DxrVrZptZxJikKErT97SIzUxb6PElWJx5fYIpSWo8T97KTv20SXnvPgsS2Xf2Elr6hCcQA32BXLHOzWWk4FE9dI7RwET8wd/Dx9uxYpBRyHo3ViQ9KInCO4e0rrYukDbm/2KWt3QimTshKtFa36/KuR2TjyDqbrNvvHQPZyi8STDwjSQUtue5UI/CbKLukqwrsVs5e8fzFfsKn0Bg0='  # 1234

token:
  expiration_time: 86400000
  # secret: user_token_native_user_service_default
  secret: '{cipher}AQCarIDe2zSWbqDEyBpoRi6/symLEQ7vdW/Cfvg0luUW3+bb//fGK+4e1ljskBzl5BCaYtGJBMfBW9uFaR/cH8XOzMY5A0i79E1iCVrXD7IYJH4GUb1w3DESEK2nCCnDlHejuXi1HxSOKwMnUus8VittbABCWi4/vyWOa6xQ4coMDfTdsTNd9It1KudtZqjOk7Svef+eiWhnSXxTk0c3vCJUOYzknFOVHkIsbSpccH14xpUcck4o0osdPtjZsvKoliFryGx/bNf/BzUFYdCYc7nIFin8pba34WLyEtWWqGTqlhjoAbjXj0eTETJF8+uW/sFk4JCGkzNNCQHN9UczGxntY/4Uv6PKVxHu6akl1EkWk4CEs/8qE1/6S5l/lWwwRl93tOcnHaRtF9aOx+Ex8IrH'

gateway:
  ip: 192.168.0.10

order_service:
  # url: http://127.0.0.1:8000/order-service/%s/orders
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    orders_is_empty: There is no item.